version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./Домашна 1/init_db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql

  springboot-app:
    build:
      context: ./Домашна 4/svscrypto
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FILTER2_THREAD_COUNT: ${FILTER2_THREAD_COUNT}
      BATCH_SIZE: ${BATCH_SIZE}
      FILTER2_DEFAULT_TIMESTAMP: ${FILTER2_DEFAULT_TIMESTAMP}
      ALPACA_API_KEY: ${ALPACA_API_KEY}
      ALPACA_API_SECRET: ${ALPACA_API_SECRET}
      NEWS_DATA_API_KEY: ${NEWS_DATA_API_KEY}
      ANALYSIS_ENGINE_URL: ${ANALYSIS_ENGINE_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  analysis-service:
    image: hristijangajdov/analysis-service:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8000
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

volumes:
  db_data:  