package com.svsbrains.svscrypto.service.impl;

import com.svsbrains.svscrypto.client.AnalysisEngineClient;
import com.svsbrains.svscrypto.client.AnalysisEngineEndpoints;
import com.svsbrains.svscrypto.model.dto.PredictionResponseDto;
import com.svsbrains.svscrypto.service.PredictionService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * Service implementation responsible for retrieving price predictions
 * generated by an external Python-based LSTM model.
 * <p>
 * This service communicates with the Analysis Engine microservice,
 * which hosts the machine learning model used for price prediction.
 * HTTP communication is delegated to {@link AnalysisEngineClient},
 * while endpoint construction is handled by {@link AnalysisEngineEndpoints}.
 * </p>
 */
@Service
@RequiredArgsConstructor
public class PythonLSTMPredictionService implements PredictionService {
    private final AnalysisEngineClient client;
    private final AnalysisEngineEndpoints endpoints;

    /**
     * Requests a price prediction for the specified cryptocurrency symbol.
     *
     * @param symbol the cryptocurrency symbol (e.g. BTC, ETH)
     * @return a {@link PredictionResponseDto} containing the predicted price data,
     *         or {@code null} if the Analysis Engine service is unavailable
     */
    @Override
    public PredictionResponseDto predictPrice(String symbol) {
        return client.get(
                endpoints.predictionEndpoint(symbol),
                PredictionResponseDto.class
        );
    }
}
